---
title: "Lecture 3: Community change in space I"
subtitle: "Global patterns of species composition: Biomes, Ecoregions, & Biogeographic regions"
author: "Gabriel Munoz"
date: "17/01/2022"
output:
  xaringan::moon_reader:
    lib_dir: assets
    seal: true
    css: ["default", "R.css", "fonts.css"]
    nature:
      beforeInit: "R-macros.js"
      highlightLines: true
      highlightStyle: github
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  cache = TRUE,
  fig.width=5, fig.height=5, 
  fig.retina=3,
  fig.align = 'center'
)
options(repos=structure(c(CRAN="http://cran.r-project.org")))
```


# About me: 

**Quantitative/Numerical Ecologist**

**Ph.D. candidate** in Biological Sciences @Concordia University

- Supervisor J.P. Lessard 

**M.Sc. Biology**, *track* Ecology and Evolution @University of Amsterdam 

**B.Sc. Biology** (*honours*) (*cum Laude*) @Universidad San Francisco de Quito 

**Minor** Environmental management @Universidad San Francisco de Quito 

<br>

<br>

**Main interests**

.alert[community assembly, community structure, multispecies interactions, Macroecology, Theoretical Ecology]

---
# Learning objectives:

<br>

<br>

#### 1) Planetary scale patterns of species coexistence/composition 

#### 2) The Earth's Biomes 

#### 3) The Earth's Biogeographic regions 

#### 4) The Earth's Ecoregions (WWF)

---
class: inverse, center, middle

# Book Part 7: Ecological Biogeography  

---
# Biogeography

- Historical biogeography 

- Ecological biogeography 

.alert[Drove my interest of a scientific career in Ecology]

.alert[Ecuador, is representative of (almost) all biomes]

---
# Mapping species coexistence 

<br>

<br>

(*Western*) Human psyche search to understand the world with discrete units 

Plato + reductionism 

* Insert image of thinking in boxes

---
# Mapping species coexistence 

|Type | Scale | Describes | 
|------------|----|-------------|
| **Biome** | Large | Plant growth form | 
| **Ecoregion** | Small | Plant growth & climate | 
| **Biogeographic region** | large | Species compositional variance | 


---
# Biomes 

* Book Map of the Earth's biomes. 

---
class: inverse, center, middle

# Chapter 23: Terrestrial Ecosystems 


---
# Chapter 23: Terrestrial Ecosystems 

*Current climate influence the spatial distribution of Biomes*


$$Climate = Precipitation \times Temperature$$ 

* Robert Whittaker image

* Classic Whittaker plot, rainfall vs air surface temperature 


---
# Chapter 23: Terrestrial Ecosystems  

*Landscape physical characteristics influence the occurence of biomes*

- Topography

- Soil type 

- Disturbances 


---
# The spatial distribution of Earth's Biomes (23.1)

### Reflection of dominance of plant growth forms 

- Trees 

- Shrubs 

- Grasses 

---
# The spatial distribution of Earth's Biomes (23.1)

*What causes patterns on the spatial distribution of plant life-forms?*

- Evolutionary processes 

- Environmentally driven adaptation of plant traits.

---
#  The spatial distribution of Earth's Biomes (23.1)

### Leaf longevity

- Key trait influencing the distribution of plant diversity 
in our planet 

- *Deciduous*: short lived foliage, live for a year/season 
Example: xxxxxx 

- *Evergreen*: long-lived foliage, live beyond a year/growing season

---
#  The spatial distribution of Earth's Biomes (23.1)

*Climate influence distribution of plant life-forms and foliage type*

*remind Whittaker plot + map of biomes 

---
#  The spatial distribution of Earth's Biomes (23.1)

*High to low temperature*

- Broad-leaf evergreen trees (*tropical and subtropical rain forest*) 

- Winter-deciduous trees (*temperate forest*)

- Needle-leaf evergreen trees (*conifer forests of taigas*)

- Tundras (*extreme cold, not support tree growth*) 

---
#  The spatial distribution of Earth's Biomes (23.1)

*Tropics* 

- Latitudinal lines where the sun can be found at a 90º zenith 


*Here Zenith-Horizon img

---
#  The spatial distribution of Earth's Biomes (23.1)

*Tropics*

- 40% of Earth Landmass 

- 40% of Earth's population (50% in 2050) 

- Surrounds the Equatorial line, between tropic of cancer and tropic of capricorn (23ºN & 23ªS)

*Here Kopen-Geiger map tropics

---
#  The spatial distribution of Earth's Biomes (23.1)

*Temperate zones*


---
#  The spatial distribution of Earth's Biomes (23.1)

*Artic & Antartic zones*

---
# 23.2 Tropical (lowland) rain forest

<br>

$$T_{mean} >18^{ºC} \\  P_{mean} > 600mm^3$$ 

- Yearly stable and warm temperatures, with copious rainfall 

- Evergreen vegetation 

- High canopies 

- Highly influenced by riverine dynamics 

- High biodiversity

---
# 23.2 Tropical (lowland) rain forest

** Picture of tropical rainforest  

---
# n.n. Tropical Cloud/Montane Forest


$$8^{ºC} < T_{mean} >20^{ºC} \\ 500 mm^3 < P_{mean} > 1\times10^4mm^3$$ 


- Outward slopes of mountain chains  (e.g. Andes)

- Typically above 1000 m.a.s.l. 

- High precipitation 

---
# n.n. Tropical Cloud/Montane Forest

- Evergreen and decidous 

- Highly endangered (Oppressed by climate change and agriculture)

- High species numbers per unit area of space and highly endemic 

- Rapid elevational changes in species composition 

---
# n.n. Tropical Cloud/Montane Forest

* Picture of a cloudforest

---
#  23.3 Tropical Savannah  (dry-forests)


* Book-Photo of tropical savanna distribution 


---
#  23.3 Tropical Savannah  (dry-forests)

Enough sunlight reaches ground to create vegetation stratified in 2 layers 

- Grasses 

- Trees or Shrubs 

.alert[Why there is trees and shrubs but rarely trubs?]


- Sites with an smooth land relief

---
#  23.3 Tropical Savannah  (dry-forests)

- Deciduous trees, fire-adapted 

- Short-lived species (woody vegetation) 

- Less than 5% of Earth's surface

- Critically endangered (Less than 1% of original extent in some TDF)

- Species poor in numbers but rich in endemism 

---
#  23.3 Tropical Savannah  (dry-forests)*

* Florecimiento guayacanes 

---
#  23.3 Tropical Savannah  (dry-forests)


$$Savannah = P_{seasonality} \times Soil_{texture}$$

** Figure 23.13 (transition grassland image)


---
# 23.4 Grasslands 

- Geographic zones with low precipitation

  - mid latitudes | mid continental  

- Dominated by grasses (Poaceae) 

- 30% to 40% of land cover

---
# 23.4 Grasslands 

- Highly sensitive to perturbations 

- Medium rich in species numbers (maybe more in some clades)

- small rodents and seed-eater birds 

- Support large populations of ruminant and predator mammals 

---
# 23.4 Grasslands 


- Human altered environments (expansion and contraction) 

- Fire and agriculture (facilitate land trade & human migration)

- Steppes | Meadows | Savannah 

---
# 23.4 Grasslands 

** Book photo of grassland distribution

---
# 23.4 Grasslands 

** Figure 23.15

** Picture of north american grasslands 

---
# 23.5 Deserts 

* Book Picture of desert distribution  
---
# 23.5 Deserts 

- Extremely arid, almost null to none precipitation

- Rain-shadow effect 

* Here image of rainshadow eff. 

- Mid-land masses 

- Cold sea and air currents 

---
# 23.5 Deserts 

- Antarctica (frozen desert) (largest desert?) 

- Salt desert* (can have precipitation) (Bolivia / AR / US / Iran)

- Arenales (graveldunes) (High altitude deserts, just below perpetual snowline)

*  salt desert photo of Bolivia

---
# 23.5 Deserts 

- Very poor in species numbers 

- inhospitable but very stable (most common ecosystem in the universe?)

---
# 23.5 Deserts 

* Picture of desert ant 

---
# 23.6 Shrublands 

* Picture of shrubland distribution 

---
# 23.6 Shrublands 

- Shrubs as dominant growth form

Picture of a shrub 

*Shrub* = woody stem & 4.5m to 8m tall 

.alert[Why there is trees and shrubs but rarely trubs?]

---
# 23.6 Shrublands 

- Chaparrales (High altitude Andean plateau, above alpine treeline, California)

* Picture of shrublands 

---
# 23.7 Temperate deciduous forests 

* Picture of temperature deciduous forest distribution 

---
# 23.7 Temperate deciduous forests 

- Forest dominated by broadleaf deciduous trees (e.g. Maple trees)

- Very little remains from original distribution, agriculture, logging, climate-change 

---
# 23.7 Temperate deciduous forests 

- Ancient forests 

* Picture of lenga 
* Picture of Laurasia and Godwana 

.alert[antartica flora]

---
# 23.7 Temperate deciduous forests 

*Picture 23.28 

Color change marks the end of the growing season 

* Picture of canadian autumm 

---
# 23.8 Temperate Coniferous Forests 

* Picture of distribution of T. coniferous forests 

---
# 23.8 Temperate Coniferous Forests 

- Canada and Russia, major shareholders 
- *a.k.a.*Boreal forest, Taiga 

- Dominated by conifers, needle-leaf evergreen trees 

- Sub-artic belt in northern hemisphere 

- High humidity, but tree growth is limited by low temperatures 

- Permafrost underneath soil

.alert[Permafrost: perennially frozen ground. Keeps ground soggy, despite low precipitation]

---
# 23.8 Temperate Coniferous Forests 

- Largest carbon storage

- Monotypic forests

- Highly invasive species in the rest of the world

---
# 23.8 Temperate Coniferous Forests 

** Book picture of Canada Boreal forest 

.alert[Treeline: the latitudinal / altitudinal limit that hinders tree growth (not establishment)
]

** Picture of a treeline. 

---
# 23.10 Tundra 

* Picture distribution of tundras 

---
# 23.10 Tundra 

- "frozen plain" located at above treelines 

- polar grassland 

- polar desert 

---
# 23.10 Tundra 

*Figure 23.37 


---
# n.n. Tropical Alpine Tundra (Páramo)

*Picture with paramo distribution

---
# n.n. Tropical Alpine Tundra (Páramo)

- High altitude ecosystem 

- Deep layer of soil (non-refrigerated permafrost) 

- Highly diverse 

- Evolutionary important 

---
# n.n. Tropical Alpine Tundra (Páramo)


- Water reservoir (acts as a sponge)

- Critically endangered 

- Agricultural expansion + Climate Change 


---
# n.n. Tropical Alpine Tundra (Páramo)

* Picure of a paramo.

---
class: inverse, center, middle

# Ecoregions 

---
# Ecoregions 

* here Olson's definition for an EcoRegion

* here Olson's map of EcoRegions 

---
# Ecoregions 

* here link to WWF Ecoregion website 

---
class: inverse, center, middle

# Biogeographic regions 

---
# Biogeographic regions 

* here Wallace definition of a biogeographic region 


---
# Wallace's Biogeographic (zoogeographic) regions 

*Biogeographic regionalization*

- Tobler's first law of Geography 

- Region names contingent on what taxa is being described

- Zoogeographic regions (Animals)

- Phytogeographic regions (Plants) 

- Microorganisms ? 

---
# Holt *et al*., 2013 update of Wallace's zoogeographic regions 

* JP's Biogeographic region figure 


---
# Transition zones 

* Morrone's image of transition zones 

---
# Transition zones 

* Map image of transition zones 


---
# Transition zones 

* Main result of Transition zone paper with Chloe + Colin 




